version: "3.7"

volumes:
  db-volume:

services:
  app:
    build:
      context: ../
      dockerfile: docker/.
    image: db-management-app:latest
    container_name: my-db-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin

  db:
    image: postgres:alpine
    restart: always
    container_name: db
    volumes:
      - db-volume:/my-volume/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin



